name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Build Binary
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64   go build -o dist/m365recon-linux-amd64
          GOOS=linux GOARCH=arm64   go build -o dist/m365recon-linux-arm64
          GOOS=darwin GOARCH=amd64  go build -o dist/m365recon-darwin-amd64
          GOOS=darwin GOARCH=arm64  go build -o dist/m365recon-darwin-arm64
          GOOS=windows GOARCH=amd64 go build -o dist/m365recon-windows-amd64.exe
      
      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            dist/*
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          